before_install: gem update --system
bundler_args: --without development
cache: bundler
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
language: ruby
rvm:
  - 2.1.9
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby-9.1.6.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
sudo: false
